name: Grotto CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Checkout
      uses: actions/checkout@master
    - name: Tests
      run: go test -v ./...
    - name: Build
      run: go build
